apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: blog
    rel: frontend
  name: frontend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: blog
      rel: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: blog
        rel: frontend
    spec:
      containers:
      - image: nginx:alpine
        name: nginx
        resources: {}
status: {}
