apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: blog
    rel: frontend
spec:
  type: ClusterIP
  selector:
    app: blog
    rel: frontend
  ports:
    - name: http
      port: 80
      targetPort: 8080
    - name: https
      port: 443
      targetPort: 8443
