apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: blog
spec:
  type: ClusterIP
  selector:
    app: blog
    rel: backend
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
