apiVersion: v1
kind: Service
metadata:
  name: mysql-pods
  labels:
    app: blog
    rel: backend
spec:
  clusterIP: None
  publishNotReadyAddresses: true
  selector:
    app: blog
    rel: backend
  ports:
  - name: mysql
    port: 3306
